version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "compose/local/backend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "compose/local/db/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "compose/production/backend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "src/requirements/"
    schedule:
      interval: "daily"
