# Generated by Django 5.0.7 on 2025-11-23 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Space Tag",
                "verbose_name_plural": "Space Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "access",
                    models.IntegerField(choices=[(0, "Full Public"), (1, "Semi Public"), (2, "Private")], default=0),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="spaces", to="users.spacetag")),
            ],
            options={
                "verbose_name": "Space",
                "verbose_name_plural": "Spaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpaceCollaborator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("permission_level", models.IntegerField(choices=[(0, "Viewer"), (1, "Admin"), (2, "Superadmin")])),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="collaborators", to="users.space"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Space Collaborator",
                "verbose_name_plural": "Space Collaborators",
                "ordering": ["-created_at"],
                "unique_together": {("space", "user")},
            },
        ),
    ]
