# Generated by Django 5.0.7 on 2025-11-23 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_spacetag_space_spacecollaborator"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spacecollaborator",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="spacecollaborator",
            name="invitation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spacecollaborator",
            name="invitation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spacecollaborator",
            name="invitation_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="spacecollaborator",
            name="invited_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="spacecollaborator",
            name="is_accepted",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="spacecollaborator",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="spacecollaborator",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="space_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="spacecollaborator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_accepted", True)), fields=("space", "user"), name="unique_accepted_collaborator"
            ),
        ),
    ]
