# Generated by Django 5.0.7 on 2025-11-23 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_spacecollaborator_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacecollaborator",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
