# Generated by Django 5.0.7 on 2025-11-23 16:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_spacecollaborator_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacecollaborator",
            name="is_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
