# Generated by Django 5.0.7 on 2025-11-27 18:27
# Manually adjusted to handle previously dropped SpaceTag tables

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


def remove_tags_field_state(apps, schema_editor):
    """
    This is a no-op for database since tables were already dropped.
    Django state will be updated by subsequent AddField.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_spacecollaborator_is_revoked"),
    ]

    operations = [
        # Create UserTag model
        migrations.CreateModel(
            name="UserTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_encrypted", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Tag",
                "verbose_name_plural": "User Tags",
                "ordering": ["-created_at"],
            },
        ),
        # Use SeparateDatabaseAndState to handle already dropped M2M table
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="space",
                    name="tags",
                ),
            ],
            database_operations=[
                # No-op: M2M table was already dropped
            ],
        ),
        # Add new tags field pointing to UserTag
        migrations.AddField(
            model_name="space",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="spaces", to="users.usertag"),
        ),
    ]
