# Generated by Django 5.0.7

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_passwordresettoken_delete_spacetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn URL"),
        ),
    ]
