# Generated by Django 5.0.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_linkedin_url"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="SpaceTag",
                ),
            ],
            database_operations=[],
        ),
    ]
