# Generated by Django 5.0.7 on 2025-01-08 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_mineralrelation_mineral_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mineralrelation",
            options={"verbose_name": "Relation", "verbose_name_plural": "RelationTree"},
        ),
    ]
