# Generated by Django 5.0.7 on 2025-06-26 12:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import erebus.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0016_alter_mineralrelation_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(help_text="Chunk name", max_length=1000)),
                (
                    "file",
                    models.FileField(
                        help_text="File chunk stored in S3",
                        max_length=1000,
                        storage=erebus.utils.ErebusStorage(),
                        upload_to=erebus.utils._get_parsed_path,
                    ),
                ),
                ("version", models.IntegerField(default=1, help_text="Version of the chunk")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Flag to indicate if the chunk should be used for further processing"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("is_major", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField(blank=True, help_text="Prompt text", null=True)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Prompt for composition extraction")], help_text="Prompt type"),
                ),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChunkIssue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(help_text="Issue name", max_length=100)),
                ("comment", models.TextField(help_text="Description")),
                ("email", models.EmailField(help_text="Email address of the reporter", max_length=254)),
                (
                    "is_resolved",
                    models.BooleanField(default=False, help_text="Flag to indicate if the issue has been resolved"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, help_text="Datetime of resolution", null=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issues", to="erebus.chunk"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="User who reported the issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk Issue",
                "verbose_name_plural": "Chunk Issues",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("major", models.PositiveIntegerField(null=True)),
                ("minor", models.PositiveIntegerField(null=True)),
                ("patch", models.PositiveIntegerField(null=True)),
            ],
            options={
                "verbose_name": "Code Version",
                "verbose_name_plural": "Code Versions",
                "ordering": ["-major", "-minor", "-patch"],
                "get_latest_by": ["-created_at"],
                "unique_together": {("major", "minor", "patch")},
            },
        ),
        migrations.AddField(
            model_name="chunk",
            name="code_version",
            field=models.ForeignKey(
                help_text="Code version used for processing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erebus.codeversion",
            ),
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=200, unique=True)),
                ("resource", models.IntegerField(choices=[(1, "DIGIS"), (2, "EREBUS")])),
                ("sample_name", models.CharField(max_length=200)),
                ("grain_size", models.TextField(default=None, null=True)),
                ("rock_name", models.CharField(default=None, max_length=200, null=True)),
                ("rock_texture", models.TextField(default=None, null=True)),
                (
                    "alteration",
                    models.IntegerField(
                        choices=[
                            (1, "Almost totally altered"),
                            (2, "Extensively altered"),
                            (3, "Fresh"),
                            (4, "Moderately altered"),
                            (5, "Slightly altered"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "primary_secondary",
                    models.IntegerField(choices=[(1, "Primary"), (2, "Secondary")], default=None, null=True),
                ),
                (
                    "tectonic_setting",
                    models.IntegerField(
                        choices=[
                            (1, "Archean Craton (including Greenstone Belts)"),
                            (2, "Complex Volcanic Settings"),
                            (3, "Continental Flood Basalt"),
                            (4, "Convergent Margin"),
                            (5, "Intraplate Volcanics"),
                            (6, "Ocean Island"),
                            (7, "Ocean-basin Flood Basalt"),
                            (8, "Oceanic Plateau"),
                            (9, "Rift Volcanics"),
                            (10, "Seamount"),
                            (11, "Submarine Ridge"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="core.mineral"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
            },
        ),
        migrations.CreateModel(
            name="ChunkResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, help_text="Raw response(s) from AI service", null=True)),
                (
                    "clean_response",
                    models.JSONField(blank=True, help_text="Parsed response from AI service", null=True),
                ),
                (
                    "is_extracted",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to indicate if structural data is extracted from the response to the database",
                    ),
                ),
                (
                    "is_error",
                    models.BooleanField(default=False, help_text="Flag to indicate if processing/extraction failed"),
                ),
                ("exception", models.TextField(blank=True, help_text="Exception message", null=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="erebus.chunk"
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="erebus.prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "ordering": ["-created_at", "-updated_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(help_text="File name", max_length=1000)),
                ("description", models.TextField(blank=True, help_text="Description of the file", null=True)),
                (
                    "file",
                    models.FileField(
                        help_text="File stored in S3",
                        max_length=1000,
                        storage=erebus.utils.ErebusStorage(),
                        upload_to=erebus.utils._get_upload_path,
                    ),
                ),
                ("size", models.PositiveIntegerField(help_text="File size in bytes", null=True)),
                ("mime_type", models.CharField(blank=True, help_text="File MIME type", max_length=200, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Queued"),
                            (1, "Parsed"),
                            (2, "AI Response(s) Generated"),
                            (3, "Processed"),
                            (4, "Parsing Failed"),
                            (5, "AI Failed"),
                            (6, "Processing Failed"),
                            (7, "Archived"),
                        ],
                        default=0,
                        help_text="Processing status",
                    ),
                ),
                (
                    "access",
                    models.IntegerField(
                        choices=[(0, "Full Public"), (1, "Semi Public"), (2, "Private")],
                        default=0,
                        help_text="Access level",
                    ),
                ),
                ("parsed_at", models.DateTimeField(blank=True, help_text="Datetime of parsing completion", null=True)),
                (
                    "ai_generated_at",
                    models.DateTimeField(blank=True, help_text="Datetime of AI response generation", null=True),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, help_text="Datetime of processing completion", null=True),
                ),
                ("archived_at", models.DateTimeField(blank=True, help_text="Datetime of archiving", null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Owner of the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File Queue",
                "verbose_name_plural": "File Queues",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="chunk",
            name="parent",
            field=models.ForeignKey(
                help_text="Parent file of the chunk",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="erebus.queue",
            ),
        ),
        migrations.CreateModel(
            name="MeasurementComponents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("unit", models.IntegerField(choices=[(1, "ppm"), (2, "ppb"), (3, "ppt"), (4, "wt)")])),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="erebus.component"
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="components", to="erebus.measurement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Component",
                "verbose_name_plural": "Measurement Components",
                "unique_together": {("measurement", "component")},
            },
        ),
    ]
