# Generated by Django 5.0.7 on 2025-03-04 19:07

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models

import erebus.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0016_alter_mineralrelation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Chunk name", max_length=1000)),
                (
                    "chunk",
                    models.FileField(
                        help_text="File chunk stored in S3",
                        storage=erebus.utils.ErebusStorage(),
                        upload_to=erebus.utils._get_parsed_path,
                    ),
                ),
                ("response", models.TextField(blank=True, help_text="Raw response from AI service", null=True)),
                (
                    "clean_response",
                    models.JSONField(blank=True, help_text="Parsed response from AI service", null=True),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, help_text="Flag to indicate if processing is over"),
                ),
                ("is_error", models.BooleanField(default=False, help_text="Flag to indicate if processing failed")),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "ordering": ["-created_at", "-updated_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("is_major", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(help_text="File name", max_length=1000)),
                ("description", models.TextField(blank=True, help_text="Description of the file", null=True)),
                (
                    "file",
                    models.FileField(
                        help_text="File stored in S3",
                        storage=erebus.utils.ErebusStorage(),
                        upload_to=erebus.utils._get_upload_path,
                    ),
                ),
                ("size", models.PositiveIntegerField(help_text="File size in bytes", null=True)),
                ("mime_type", models.CharField(blank=True, help_text="File MIME type", max_length=200, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Queued"), (1, "Parsed"), (2, "Processed"), (3, "Failed"), (4, "Archived")],
                        default=0,
                        help_text="Processing status",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Queue",
                "verbose_name_plural": "File Queues",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=200, unique=True)),
                ("resource", models.IntegerField(choices=[(1, "DIGIS"), (2, "EREBUS")])),
                ("sample_name", models.CharField(max_length=200)),
                ("grain_size", models.TextField(default=None, null=True)),
                ("rock_name", models.CharField(default=None, max_length=200, null=True)),
                ("rock_texture", models.TextField(default=None, null=True)),
                (
                    "alteration",
                    models.IntegerField(
                        choices=[
                            (1, "Almost totally altered"),
                            (2, "Extensively altered"),
                            (3, "Fresh"),
                            (4, "Moderately altered"),
                            (5, "Slightly altered"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "primary_secondary",
                    models.IntegerField(choices=[(1, "Primary"), (2, "Secondary")], default=None, null=True),
                ),
                (
                    "tectonic_setting",
                    models.IntegerField(
                        choices=[
                            (1, "Archean Craton (including Greenstone Belts)"),
                            (2, "Complex Volcanic Settings"),
                            (3, "Continental Flood Basalt"),
                            (4, "Convergent Margin"),
                            (5, "Intraplate Volcanics"),
                            (6, "Ocean Island"),
                            (7, "Ocean-basin Flood Basalt"),
                            (8, "Oceanic Plateau"),
                            (9, "Rift Volcanics"),
                            (10, "Seamount"),
                            (11, "Submarine Ridge"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="core.mineral"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
            },
        ),
        migrations.CreateModel(
            name="QueueChunkThrough",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="erebus.chunk")),
                ("queue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="erebus.queue")),
            ],
            options={
                "verbose_name": "Queue Chunk Through",
                "verbose_name_plural": "Queue Chunk Throughs",
                "unique_together": {("queue", "chunk")},
            },
        ),
        migrations.AddField(
            model_name="queue",
            name="chunks",
            field=models.ManyToManyField(
                help_text="Parsed Chunks of the file", through="erebus.QueueChunkThrough", to="erebus.chunk"
            ),
        ),
        migrations.CreateModel(
            name="MeasurementComponents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("unit", models.IntegerField(choices=[(1, "ppm"), (2, "ppb"), (3, "ppt"), (4, "wt)")])),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="erebus.component"
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="components", to="erebus.measurement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Component",
                "verbose_name_plural": "Measurement Components",
                "unique_together": {("measurement", "component")},
            },
        ),
    ]
