# Generated by Django 5.0.7 on 2025-04-18 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chunk",
            old_name="chunk",
            new_name="file",
        ),
    ]
