# Generated by Django 5.0.7 on 2025-08-22 19:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Prompt for composition extraction"), (1, "Prompt for metadata extraction")],
                help_text="Prompt type",
            ),
        ),
    ]
