# Generated by Django 5.0.7 on 2025-03-18 11:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="processed_at",
            field=models.DateTimeField(blank=True, help_text="Processed at", null=True),
        ),
    ]
