# Generated by Django 5.0.7 on 2025-08-27 18:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0002_alter_prompt_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="head",
            field=models.JSONField(
                blank=True, help_text="Table head preview (first few rows) for frontend display", null=True
            ),
        ),
    ]
