# Generated by Django 5.0.7 on 2025-05-17 14:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0002_rename_chunk_chunk_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="version",
            field=models.IntegerField(default=1, help_text="Version of the chunk"),
        ),
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Parsed"),
                    (2, "Processed"),
                    (3, "Parsing Failed"),
                    (4, "Processing Failed"),
                    (5, "Archived"),
                ],
                default=0,
                help_text="Processing status",
            ),
        ),
    ]
