# Generated by Django 5.0.7 on 2025-03-10 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0003_alter_queue_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who uploaded the file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
