# Generated by Django 5.0.7 on 2025-08-28 11:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0003_chunk_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunkresponse",
            name="model",
            field=models.CharField(
                default="gpt-5-nano", help_text="Model used for response generation", max_length=100
            ),
            preserve_default=False,
        ),
    ]
