# Generated by Django 5.0.7 on 2025-05-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0003_chunk_version_alter_queue_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.IntegerField(default=1, help_text="Version of the prompt")),
                ("prompt", models.TextField(help_text="Prompt text")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Extract numerical data"), (1, "Extract metadata")], help_text="Prompt type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="clean_response",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="is_error",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="response",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="user",
        ),
        migrations.AddField(
            model_name="queue",
            name="access",
            field=models.IntegerField(
                choices=[(0, "Full Public"), (1, "Semi Public"), (2, "Private")], default=0, help_text="Access level"
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="ai_generated_at",
            field=models.DateTimeField(blank=True, help_text="Datetime of AI response generation", null=True),
        ),
        migrations.AddField(
            model_name="queue",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Owner of the file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Parsed"),
                    (2, "AI Response(s) Generated"),
                    (3, "Processed"),
                    (3, "Parsing Failed"),
                    (4, "AI Failed"),
                    (5, "Processing Failed"),
                    (6, "Archived"),
                ],
                default=0,
                help_text="Processing status",
            ),
        ),
        migrations.CreateModel(
            name="ChunkResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, help_text="Raw response(s) from AI service", null=True)),
                (
                    "clean_response",
                    models.JSONField(blank=True, help_text="Parsed response from AI service", null=True),
                ),
                (
                    "is_extracted",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to indicate if structural data is extracted from the response to the database",
                    ),
                ),
                (
                    "is_error",
                    models.BooleanField(default=False, help_text="Flag to indicate if processing/extraction failed"),
                ),
                ("exception", models.TextField(blank=True, help_text="Exception message", null=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="erebus.chunk"
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="erebus.prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "ordering": ["-created_at", "-updated_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
    ]
