# Generated by Django 5.0.7 on 2025-05-30 14:12

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0004_prompt_remove_chunk_clean_response_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chunk",
            options={
                "get_latest_by": ["-created_at"],
                "ordering": ["-created_at"],
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
            },
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="chunk",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Flag to indicate if the chunk should be used for further processing"
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="archived_at",
            field=models.DateTimeField(blank=True, help_text="Datetime of archiving", null=True),
        ),
        migrations.CreateModel(
            name="ChunkIssue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(help_text="Issue name", max_length=100)),
                ("comment", models.TextField(help_text="Description")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, help_text="Flag to indicate if the issue has been resolved"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issues", to="erebus.chunk"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk Issue",
                "verbose_name_plural": "Chunk Issues",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
    ]
