# Generated by Django 5.0.7 on 2025-08-28 12:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0004_chunkresponse_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="Flag to indicate if the chunk should be used for further processing/extraction"
            ),
        ),
    ]
