# Generated by Django 5.0.7 on 2025-06-11 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0005_alter_chunk_options_remove_chunk_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(help_text="version name", max_length=100)),
            ],
            options={
                "verbose_name": "Code Version",
                "verbose_name_plural": "Code Versions",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chunkissue",
            name="email",
            field=models.EmailField(default="1.0.0", help_text="Email address of the reporter", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chunkissue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who reported the issue",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="code_version",
            field=models.ForeignKey(
                help_text="Code version used for processing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erebus.codeversion",
            ),
        ),
    ]
