# Generated by Django 5.0.7 on 2025-08-28 12:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0005_alter_chunk_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chunk",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="chunk",
            name="extract_composition",
            field=models.BooleanField(
                default=True, help_text="Flag to indicate if the chunk should be used for extracting composition"
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="extract_metadata",
            field=models.BooleanField(
                default=True, help_text="Flag to indicate if the chunk should be used for extracting metadata"
            ),
        ),
    ]
