# Generated by Django 5.0.7 on 2025-06-12 08:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0006_codeversion_chunkissue_email_chunkissue_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeversion",
            name="name",
            field=models.CharField(help_text="version name", max_length=100, unique=True),
        ),
    ]
