# Generated by Django 5.0.7 on 2025-08-31 12:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0006_remove_chunk_is_approved_chunk_extract_composition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chunk",
            name="file",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="head",
        ),
        migrations.AddField(
            model_name="chunk",
            name="data",
            field=models.JSONField(help_text="Raw data from the chunk", null=True),
        ),
    ]
