# Generated by Django 5.0.7 on 2025-09-02 14:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0007_remove_chunk_file_remove_chunk_head_chunk_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chunk",
            name="name",
        ),
        migrations.AddField(
            model_name="chunk",
            name="hash",
            field=models.CharField(null=False, help_text="Hash of the chunk", max_length=21),
        ),
    ]
