# Generated by Django 5.0.7 on 2025-09-02 15:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0008_remove_chunk_name_chunk_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="hash",
            field=models.CharField(help_text="Hash of the chunk", max_length=21, null=True),
        ),
    ]
