# Generated by Django 5.0.7 on 2025-09-30 18:16

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0009_alter_chunk_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hash", models.CharField(help_text="Hash of the chunk", max_length=21, null=True)),
                (
                    "model",
                    models.CharField(choices=[("gpt-5-nano", "GPT-5 Nano")], help_text="Model used for processing"),
                ),
                (
                    "prompt_text",
                    models.TextField(blank=True, help_text="Prompt text used for response generation", null=True),
                ),
                (
                    "response_raw",
                    models.TextField(blank=True, help_text="Raw response text from AI service", null=True),
                ),
                (
                    "response_parsed",
                    models.JSONField(blank=True, help_text="Parsed response from AI service", null=True),
                ),
                (
                    "is_error",
                    models.BooleanField(default=False, help_text="Flag to indicate if processing/extraction failed"),
                ),
                ("exception", models.TextField(blank=True, help_text="Exception message", null=True)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, help_text="Datetime of processing completion", null=True),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="erebus.prompt",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="erebus.queue"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Response",
                "verbose_name_plural": "AI Responses",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIResponseChunk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order of chunk in the AI response processing"),
                ),
                (
                    "ai_response",
                    models.ForeignKey(
                        help_text="AI response",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_associations",
                        to="erebus.airesponse",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        help_text="Chunk used in AI response",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_associations",
                        to="erebus.chunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Response Chunk",
                "verbose_name_plural": "AI Response Chunks",
                "ordering": ["ai_response", "order"],
                "unique_together": {("ai_response", "chunk")},
            },
        ),
        migrations.AddField(
            model_name="airesponse",
            name="chunks",
            field=models.ManyToManyField(
                related_name="ai_responses", through="erebus.AIResponseChunk", to="erebus.chunk"
            ),
        ),
        migrations.DeleteModel(
            name="ChunkResponse",
        ),
    ]
