# Generated by Django 5.0.7 on 2025-10-01 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0010_unit_airesponse_airesponsechunk_airesponse_chunks_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airesponsechunk",
            options={
                "ordering": ["-id"],
                "verbose_name": "AI Response Chunk",
                "verbose_name_plural": "AI Response Chunks",
            },
        ),
        migrations.RemoveField(
            model_name="airesponsechunk",
            name="order",
        ),
    ]
