# Generated by Django 5.0.7 on 2025-10-13 18:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0011_alter_airesponsechunk_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airesponse",
            old_name="prompt_text",
            new_name="request_raw",
        ),
        migrations.AddField(
            model_name="airesponse",
            name="answered_at",
            field=models.DateTimeField(blank=True, help_text="Datetime of response generation", null=True),
        ),
    ]
