# Generated by Django 5.0.7 on 2025-10-18 14:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0012_rename_prompt_text_airesponse_request_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesponse",
            name="batch",
            field=models.CharField(help_text="Batch identifier for processing", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, help_text="Datetime of response generation", null=True),
        ),
    ]
