# Generated by Django 5.0.7 on 2025-10-28 17:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0013_airesponse_batch_airesponse_scheduled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesponse",
            name="completion_tokens",
            field=models.IntegerField(blank=True, help_text="Number of tokens used in completion", null=True),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, help_text="Number of tokens used in prompt", null=True),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="total_tokens",
            field=models.IntegerField(blank=True, help_text="Total number of tokens used", null=True),
        ),
    ]
