# Generated by Django 5.0.7 on 2025-10-28 19:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0014_airesponse_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"verbose_name": "Unit", "verbose_name_plural": "Units"},
        ),
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Parsed"),
                    (3, "AI Response(s) Generated"),
                    (4, "Processed"),
                    (5, "Parsing Failed"),
                    (6, "AI Failed"),
                    (7, "Processing Failed"),
                    (8, "Archived"),
                ],
                default=0,
                help_text="Processing status",
            ),
        ),
    ]
