# Generated by Django 5.0.7 on 2025-11-03 19:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0015_alter_unit_options_alter_queue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Parsed"),
                    (2, "AI Requested"),
                    (3, "AI Response(s) Generated"),
                    (4, "Processed"),
                    (5, "Parsing Failed"),
                    (6, "AI Failed"),
                    (7, "Processing Failed"),
                    (8, "Archived"),
                ],
                default=0,
                help_text="Processing status",
            ),
        ),
    ]
