# Generated by Django 5.0.7 on 2025-11-04 18:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0016_alter_queue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airesponse",
            name="model",
            field=models.CharField(
                choices=[("gpt-5-nano", "GPT-5 Nano"), ("gpt-5-mini", "GPT-5 Mini")],
                help_text="Model used for processing",
            ),
        ),
    ]
