# Generated by Django 5.0.7 on 2025-11-05 17:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0017_alter_airesponse_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airesponse",
            name="model",
            field=models.CharField(
                choices=[("gpt-5-nano", "GPT-5 Nano"), ("gpt-5-mini-2025-08-07", "GPT-5 Mini")],
                help_text="Model used for processing",
            ),
        ),
    ]
