# Generated by Django 5.0.7 on 2025-11-05 17:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0018_alter_airesponse_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="openai_id",
            field=models.CharField(help_text="OpenAI ID of the prompt", max_length=255, null=True),
        ),
    ]
