# Generated by Django 5.0.7 on 2025-11-05 18:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0019_prompt_openai_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airesponse",
            name="completion_tokens",
        ),
        migrations.RemoveField(
            model_name="airesponse",
            name="prompt_tokens",
        ),
        migrations.AddField(
            model_name="airesponse",
            name="input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="output_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="airesponse",
            name="total_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
