# Generated by Django 5.0.7 on 2025-11-13 09:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0020_remove_airesponse_completion_tokens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Prompt Tag",
                "verbose_name_plural": "Prompt Tags",
            },
        ),
        migrations.AlterField(
            model_name="prompt",
            name="openai_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PromptType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("tags", models.ManyToManyField(to="erebus.prompttag")),
            ],
            options={
                "verbose_name": "Prompt Tag",
                "verbose_name_plural": "Prompt Tags",
            },
        ),
        migrations.AlterField(
            model_name="prompt",
            name="type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prompts", to="erebus.prompttype"
            ),
        ),
    ]
