# Generated by Django 5.0.7 on 2025-11-13 10:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0021_prompttag_alter_prompt_openai_id_alter_prompt_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompttag",
            old_name="name",
            new_name="key",
        ),
        migrations.AddField(
            model_name="prompttag",
            name="value",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
