# Generated by Django 5.0.7 on 2025-11-17 11:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0022_rename_name_prompttag_key_prompttag_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="markdown",
            field=models.TextField(blank=True, null=True),
        ),
    ]
