# Generated by Django 5.0.7 on 2025-11-17 14:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0023_queue_markdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airesponse",
            name="chunks",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="chunkissue",
            name="chunk",
        ),
        migrations.RemoveField(
            model_name="chunkissue",
            name="user",
        ),
        migrations.AddField(
            model_name="queue",
            name="hash",
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "AI Requested"),
                    (2, "AI Response(s) Generated"),
                    (3, "Processed"),
                    (4, "Parsing Failed"),
                    (5, "AI Failed"),
                    (6, "Processing Failed"),
                    (7, "Archived"),
                ],
                default=0,
                help_text="Processing status",
            ),
        ),
        migrations.DeleteModel(
            name="AIResponseChunk",
        ),
        migrations.DeleteModel(
            name="Chunk",
        ),
        migrations.DeleteModel(
            name="ChunkIssue",
        ),
    ]
