# Generated by Django 5.0.7 on 2025-11-17 14:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0024_remove_airesponse_chunks_remove_chunk_code_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="extract_composition",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="queue",
            name="extract_metadata",
            field=models.BooleanField(default=True),
        ),
    ]
