# Generated by Django 5.0.7 on 2025-11-23 14:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0025_queue_extract_composition_queue_extract_metadata"),
        ("users", "0003_spacetag_space_spacecollaborator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="parsed_at",
        ),
        migrations.AddField(
            model_name="queue",
            name="space",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Space associated with the file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queues",
                to="users.space",
            ),
        ),
    ]
