# Generated by Django 5.0.7 on 2026-06-28 00:00

import erebus.utils
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erebus", "0026_remove_queue_parsed_at_queue_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="file",
            field=models.FileField(help_text="Stored file", max_length=1000, upload_to=erebus.utils._get_upload_path),
        ),
    ]
