# Generated by Django 5.0.7 on 2026-05-12 15:31

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_squashed_0003_alter_post_options_category_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="authors",
            field=models.ManyToManyField(blank=True, related_name="posts", to=settings.AUTH_USER_MODEL),
        ),
    ]
