# Generated by Django 5.0.7 on 2026-06-29 16:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="content_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="post",
            name="stone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="channels",
            field=models.ManyToManyField(blank=True, related_name="posts", to="blog.channel"),
        ),
    ]
