# Generated by Django 5.0.7 on 2025-01-08 14:49

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0016_alter_mineralrelation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=200, unique=True)),
                ("resource", models.IntegerField(choices=[(1, "DIGIS")])),
                ("sample_name", models.CharField(max_length=200)),
                ("grain_size", models.TextField(default=None, null=True)),
                ("rock_name", models.CharField(default=None, max_length=200, null=True)),
                ("rock_texture", models.TextField(default=None, null=True)),
                (
                    "alteration",
                    models.IntegerField(
                        choices=[
                            (1, "Almost totally altered"),
                            (2, "Extensively altered"),
                            (3, "Fresh"),
                            (4, "Moderately altered"),
                            (5, "Slightly altered"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "primary_secondary",
                    models.IntegerField(choices=[(1, "Primary"), (2, "Secondary")], default=None, null=True),
                ),
                (
                    "tectonic_setting",
                    models.IntegerField(
                        choices=[
                            (1, "Archean Craton (including Greenstone Belts)"),
                            (2, "Complex Volcanic Settings"),
                            (3, "Continental Flood Basalt"),
                            (4, "Convergent Margin"),
                            (5, "Intraplate Volcanics"),
                            (6, "Ocean Island"),
                            (7, "Ocean-basin Flood Basalt"),
                            (8, "Oceanic Plateau"),
                            (9, "Rift Volcanics"),
                            (10, "Seamount"),
                            (11, "Submarine Ridge"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="core.mineral"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
            },
        ),
        migrations.CreateModel(
            name="MeasurementComponents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("unit", models.IntegerField(choices=[(1, "ppm"), (2, "ppb"), (3, "ppt"), (4, "wt%)")])),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="chem.component"
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="components", to="chem.measurement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Component",
                "verbose_name_plural": "Measurement Components",
                "unique_together": {("measurement", "component")},
            },
        ),
    ]
