# Generated by Django 5.0.7 on 2025-01-21 11:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="elevation_max",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="elevation_min",
            field=models.FloatField(default=None, null=True),
        ),
    ]
