# Generated by Django 5.0.7 on 2025-01-21 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chem", "0002_measurement_elevation_max_measurement_elevation_min"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="location_comment",
            new_name="location_note",
        ),
    ]
