# Generated by Django 5.0.7 on 2025-01-21 14:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chem", "0003_rename_location_comment_measurement_location_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="primary_secondary",
        ),
        migrations.AddField(
            model_name="measurement",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
