# Generated by Django 5.0.7 on 2026-06-25 16:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoneColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "hex",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        validators=[django.core.validators.RegexValidator(regex="^#[0-9a-fA-F]{6}$")],
                    ),
                ),
            ],
            options={
                "verbose_name": "Stone color",
                "verbose_name_plural": "Stone colors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoneCut",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Stone cut",
                "verbose_name_plural": "Stone cuts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoneTreatment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Stone treatment",
                "verbose_name_plural": "Stone treatments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("mineral", models.CharField(blank=True, max_length=100, null=True)),
                ("item_number", models.CharField(blank=True, max_length=100, null=True)),
                ("weight_carats", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("price_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("price_eur", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("shipment_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("shipment_eur", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("vat_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("vat_eur", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("gross_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("gross_eur", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("adjusted_price_eur", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("adjusted_price_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("selling_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("sold_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_selling", models.BooleanField(default=False)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stones",
                        to="store.stonecolor",
                    ),
                ),
                (
                    "cut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stones",
                        to="store.stonecut",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stones",
                        to="store.stonetreatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stone",
                "verbose_name_plural": "Stones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoneImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=1024)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.stone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stone image",
                "verbose_name_plural": "Stone images",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
