# Generated by Django 5.0.7 on 2026-06-28 13:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("stone", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("owner_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("owner_telephone", models.CharField(blank=True, max_length=50, null=True)),
                ("public", models.BooleanField(default=False)),
                ("shape_cutting_style", models.CharField(blank=True, max_length=255, null=True)),
                ("measurements", models.CharField(blank=True, max_length=255, null=True)),
                ("carat_weight", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("specific_gravity", models.CharField(blank=True, max_length=255, null=True)),
                ("refractive_index", models.CharField(blank=True, max_length=255, null=True)),
                ("double_refraction", models.CharField(blank=True, max_length=255, null=True)),
                ("polariscope", models.CharField(blank=True, max_length=255, null=True)),
                ("pleochroism", models.CharField(blank=True, max_length=255, null=True)),
                ("chelsea_color_filter", models.CharField(blank=True, max_length=255, null=True)),
                ("fluorescence_sw", models.CharField(blank=True, max_length=255, null=True)),
                ("fluorescence_lw", models.CharField(blank=True, max_length=255, null=True)),
                ("microscope", models.TextField(blank=True, null=True)),
                ("treatment", models.CharField(blank=True, max_length=255, null=True)),
                ("origin", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True, choices=[("USD", "USD"), ("EUR", "EUR"), ("UAH", "UAH")], max_length=3, null=True
                    ),
                ),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "linked_stone",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report",
                        to="store.stone",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gem_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=1024)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                ("is_headline", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.report"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report image",
                "verbose_name_plural": "Report images",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
